### ISSUE TITLE
Unhandled exception when using Asset Database to export a texture to file.

### ISSUE THREAD

**Issue by HylianSteel** [Mgamerz/ME3Explorer#286]
When using Asset Database to extract a texture, an unhandled exception is thrown and it's specifically mentioning Texconverter.dll.

**To Reproduce**
1. Open Legendary Explorer,
2. Select and open Asset Database.
3. Select the LE2 Database and filter for biog_hmf_mir
4. choose something such as her loyalty outfit specular map or diffuse.
5. click Export to file and select your destination.
6. unhandled exception is thrown.

**Expected behavior**
TexConverter.dll should be located and the selected texture should be exported to wherever you selected it to be placed.

**Version information:**
6.0 7/29/2021

**Stack trace**
> DllNotFoundException: Unable to load DLL 'TexConverter.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at LegendaryExplorerCore.Textures.TexConverter.TCSaveTexture(TextureBuffer* inputBuffer, String outputFilename)
   at LegendaryExplorerCore.Textures.TexConverter.SaveTexture(Byte[] pixelData, UInt32 width, UInt32 height, PixelFormat pixelFormat, String filename) in C:\Users\Mgamerz\source\repos\ME3Explorer\LegendaryExplorer\LegendaryExplorerCore\Textures\TexConverter.cs:line 283
   at LegendaryExplorerCore.Unreal.Classes.Texture2D.ExportToFile(String outputPath) in C:\Users\Mgamerz\source\repos\ME3Explorer\LegendaryExplorer\LegendaryExplorerCore\Unreal\Classes\Texture2D.cs:line 838
   at LegendaryExplorer.UserControls.ExportLoaderControls.TextureViewerExportLoader.ExportToPNG() in C:\Users\Mgamerz\source\repos\ME3Explorer\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\TextureViewerExportLoader.xaml.cs:line 302
   at LegendaryExplorer.SharedUI.GenericCommand.Execute(Object parameter) in C:\Users\Mgamerz\source\repos\ME3Explorer\LegendaryExplorer\LegendaryExplorer\SharedUI\Commands.cs:line 52
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Mgamerz** [comment]
Use Nightly from ME3Tweaks Mod Manager's tools menu. The stable build was built incorrectly and uses debug libraries most end users probably don't have installed. The "stable" build is just a nightly we named as stable simply cause we haven't had time to stabilize things (and Nexus staff would not stop hounding us to produce a stable build).

This will be fixed when we post 6.0.1, which will probably be fairly soon.

**Comment by Mgamerz** [comment]
This was fixed in Stable 6.1.
