### ISSUE TITLE
Can't export FaceFX Json

### ISSUE THREAD

**Issue by linkenski** [Mgamerz/ME3Explorer#340]
On the latest Nightly Build I can't export to Json from the FaceFX window.

**To Reproduce**
Select a start and end time after selecting "Export Section of Line" and it throws and error

**Expected behavior**
I should be able to save a .json file with the FaceFX data as I could in older builds.

**Version information:**
Nightly 6.2 08-09-2022

**Stack trace**
ArgumentException: An item with the same key has already been added. Key: G_WeightShiftLeft
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at LegendaryExplorer.UserControls.ExportLoaderControls.FaceFXAnimSetEditorControl.ExpLineSec_Click(Object sender, RoutedEventArgs e) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\FaceFXAnimSetEditorControl.xaml.cs:line 799
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Other info**
Ran into bug in Mass Effect 3 (2012) "OT" version. Bug did not exist in other recent builds.

**Comment by linkenski** [comment]
I see the error right before me. Laugh away at this incredible realization.
