### ISSUE TITLE
Crash in pathfinding editor

### ISSUE THREAD

**Issue by mirh** [Mgamerz/ME3Explorer#360]
**Describe the bug**
Title

**To Reproduce**
1. Open `ME1\CookedPC\Maps\ICE\ART\BIOA_ICE50_00_ART.SFM` in pathfinding editor

**Expected behavior**
Don't crash

**Version information:**
v6.3.0.5143

**Stack trace**
This happens when pathfinding editor is called from package editor
```
NullReferenceException: Object reference not set to an instance of an object.
   at LegendaryExplorer.Tools.PathfindingEditor.PathfindingEditorWindow.LoadFile(String fileName, Action loadPackageDelegate) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\PathfindingEditor\PathfindingEditorWindow.xaml.cs:line 784
   at LegendaryExplorer.Tools.PathfindingEditor.PathfindingEditorWindow.<PathfindingEditorWPF_Loaded>b__354_0() in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\PathfindingEditor\PathfindingEditorWindow.xaml.cs:line 652
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
This is when I open it directly from pathfinding editor
```
NullReferenceException: Object reference not set to an instance of an object.
   at LegendaryExplorer.Tools.PathfindingEditor.PathfindingEditorWindow.LoadFile(String fileName, Action loadPackageDelegate) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\PathfindingEditor\PathfindingEditorWindow.xaml.cs:line 784
   at LegendaryExplorer.Tools.PathfindingEditor.PathfindingEditorWindow.<.ctor>b__347_0(String x) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\PathfindingEditor\PathfindingEditorWindow.xaml.cs:line 572
   at LegendaryExplorer.UserControls.SharedToolControls.RecentsControl.<LoadCommands>b__14_0(Object filePath) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\SharedToolControls\RecentsControl.xaml.cs:line 86
   at LegendaryExplorer.SharedUI.RelayCommand.Execute(Object parameter) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\SharedUI\Commands.cs:line 24
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Mgamerz** [comment]
This should be fixed in the next nightly build. It looks like this issue has existed for some time, when the initial GPS code was added. ME1 doesn't have any LEX-Game interop so it was failing when it was accessed loading a package.

Thanks for the detailed report.
