### ISSUE TITLE
Mass Effect 1 (OT1) dialogue nodes can not be opened in InterpEditor

### ISSUE THREAD

**Issue by vegz** [Mgamerz/ME3Explorer#387]
**Describe the bug**
Opening a dialogue node with a "BioEvtSysTrackSwtichCamera" in OT1 will cause an error to pop up that says "Unknown Track Type: BioEvtSysTrackSwitchCamera" and the interp for a node will not open.

**To Reproduce**
1. Open BIOA_END20_02_DSG (ME1) in dialogue editor
2. Go to end20_avina_dlg and click on Entry Node 0
3.  Go to matinee and press "Open this line in interpeditor"
4.  The error should then pop up

**Expected behavior**
The InterpData for the node should open up correctly and show what is going on in the file. The file opens fine in the LE1 version of the game but doesn't in OT1.

**Screenshots and files used to replicate this**
BIOA_END20_02_DSG 

**Version information:**
6.3 NIGHTLY 7/10/2023

**Stack trace**
FormatException: Unknown Track Type: BioEvtSysTrackSwitchCamera
   at LegendaryExplorer.Tools.InterpEditor.InterpTrack.CreateInterpTrackForExport(ExportEntry trackExport) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\InterpDataTimeline\InterpEditorTracks.cs:line 170
   at LegendaryExplorer.Tools.InterpEditor.InterpGroup.RefreshTracks() in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\InterpDataTimeline\InterpEditorTracks.cs:line 51
   at LegendaryExplorer.Tools.InterpEditor.InterpGroup..ctor(ExportEntry export) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\InterpDataTimeline\InterpEditorTracks.cs:line 39
   at LegendaryExplorer.UserControls.ExportLoaderControls.Timeline.<>c.<LoadGroups>b__53_4(ExportEntry exp) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\InterpDataTimeline\Timeline.xaml.cs:line 204
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at LegendaryExplorerCore.Misc.ObservableCollectionExtended`1.AddRange(IEnumerable`1 collection) in D:\a\1\s\LegendaryExplorer\LegendaryExplorerCore\Misc\ObservableCollectionExtended.cs:line 69
   at LegendaryExplorer.UserControls.ExportLoaderControls.Timeline.LoadGroups() in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\InterpDataTimeline\Timeline.xaml.cs:line 204
   at LegendaryExplorer.UserControls.ExportLoaderControls.Timeline.LoadExport(ExportEntry exportEntry) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\UserControls\ExportLoaderControls\InterpDataTimeline\Timeline.xaml.cs:line 33
   at LegendaryExplorer.Tools.InterpEditor.InterpEditorWindow.LoadInterpData(ExportEntry value) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\InterpEditor\InterpEditorWindow.xaml.cs:line 165
   at LegendaryExplorer.Tools.InterpEditor.InterpEditorWindow.set_SelectedInterpData(ExportEntry value) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\InterpEditor\InterpEditorWindow.xaml.cs:line 104
   at LegendaryExplorer.DialogueEditor.DialogueEditorWindow.OpenInInterpViewer_Clicked(ExportEntry exportEntry) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\Dialogue Editor\DialogueEditorWindow.xaml.cs:line 3127
   at LegendaryExplorer.DialogueEditor.DialogueEditorWindow.OpenInAction(Object obj) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\Tools\Dialogue Editor\DialogueEditorWindow.xaml.cs:line 3238
   at LegendaryExplorer.SharedUI.RelayCommand.Execute(Object parameter) in D:\a\1\s\LegendaryExplorer\LegendaryExplorer\SharedUI\Commands.cs:line 24
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Other information**
n/a

**Comment by Mgamerz** [comment]
The switch statement for the parser for tracks doesn't have this - I added it, but it appears there's more that also are not parsed.
